### ISSUE TITLE
Nuclei Dataset

### ISSUE THREAD

**Issue by nikku1234** [huiqu18/TDGAN-PyTorch#1]
Can you please share the nuclei dataset used in the paper?

**Comment by huiqu18** [comment]
@nikku1234 You can find the dataset here: https://drive.google.com/drive/folders/1LQQIGLNg5vMELtLD4UJdDT2OjTMZMlcn?usp=sharing
Original images are in `Tissue images.zip`. Nuclei contours can be extracted from instance labels.

**Comment by nikku1234** [comment]
Thanks!
